name: Deploy to Dokku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Dokku Server
        uses: dokku/github-action@master
        with:
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}:${{ secrets.DOKKU_PORT }}/runtime-bot
          ssh_private_key: ${{ secrets.DOKKU_KEY }}